FROM python:3.8-slim-bullseye

# Set the working directory in the container
WORKDIR /code

# Copy application files into the container
COPY . /code/

# Install dependencies
RUN pip install -r requirements.txt

# Expose port 8888
EXPOSE 8888

# Run the FastAPI application
CMD ["uvicorn", "app_1:app", "--host", "0.0.0.0", "--port", "8888"]